// 在此处添加您的代码
namespace jason_room {
    export function main() {
        let statusbar2: StatusBarSprite = null
        let jason_mySprite: Sprite = null
        let ha: Sprite = null
        game.splash("躲避菜刀，打败菜刀")
        tiles.setTilemap(tilemap`jason_level1`)

        jason_mySprite = sprites.create(img`
        ...........222222ee.............
        .........2233333bbeee...........
        .......2233d1111333bee..........
        ......23ddd111dd1d33eee.........
        .....23d1333d1d33d13bee.........
        ....23d133333d1d33313eee........
        ...2311333333ddd3333dbeee.......
        ..2313333333333ddd33d3e44e......
        ..21d3333333333ddd333db44ee.....
        .2313333333333dd33333db444ee....
        .2dd3333333333d333333d3b444e....
        2311d333333333d333333ddbb444e...
        2d131d33333333d333333d1b6644e...
        2d33dd33333333d333333d1b44444e..
        21333d3333333d3333333d1644664ee.
        21333d333333d33333333d16b64464be
        21333dddd33dd33333333d1646446b6e
        2133333dd11dd33333333d1644b6446e
        e133333d1d31d33333333d1b4446446e
        e1333331d3331333333331d6bb44b6e.
        e1333331dd331b3333333136bb6bb6e.
        e13333331dd1db33333331b6b66bbe..
        edd33333311db3333333dd6bb6bbe...
        e3d3333333d333333333136beebbe...
        .edd3333333d3333333ddbfeebbe....
        .e3dd33333dd3333333d3efeeee.....
        ..e3dd333d1333333dd3bfffff......
        ...e311111ddd333dddbffeef.......
        ....eed1d33d111113befeff........
        ......eeb333dd13beffff..........
        ........eeeefffffee.............
        ................................
        `, SpriteKind.Player)
        tiles.placeOnTile(jason_mySprite, tiles.getTileLocation(7, 7))
        controller.moveSprite(jason_mySprite)
        scene.cameraFollowSprite(jason_mySprite)
        statusbar2 = statusbars.create(40, 4, StatusBarKind.Health)
        statusbar2.attachToSprite(jason_mySprite)
        statusbar2.value = 100
    
    

        info.startCountdown(60)
        ha = sprites.create(img`
    ...bbbbbbbbbbbbbbbbbbbb..
    ...b11bbbbbbbbbbbbbbbbb..
    ...b11bbbbbbbbbbbbbbbbb..
    ...bbbbbbbbbbbbbbbbbbbb..
    ...bbbbbbbbbbbbbbbbbbbb..
    ...bbbbbbbbbbbbbbbbbbbb..
    ...bbbbbbbbbbbbbbbbbbbb..
    ...bbbbbbbbbbbbbbbbbbbb..
    ...bbbbbbbbbbbbbbbbbbbb..
    ...bbbbbbbbbbbbbbbbbbbb..
    ...bbbbbbbbbbbbbbbbbbbb..
    ...bbbbbbbbbbbbbbbbbbbb..
    ...bbbbbbbbbbbbbbbbbbbb..
    ...bbbbbbbbbbbbbbbbbbbb..
    ...bbbbbbbbbbbbbbbbbbbb..
    ...ffffffbbbbbbbbbbbbbb..
    ...ffffffbbbbbbbbbbbbbb..
    ...ffffffbbbbbbbbbbbbbb..
    ...ffffff................
    ...ffffff................
    ...ffffff................
    ...ffffff................
    ...ffffff................
    ...ffffff................
    ...ffffff................
    `, SpriteKind.Enemy)
        ha.follow(jason_mySprite, 30)
        sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
            animation.runImageAnimation(
                ha,
                [img`
        ...bbbbbbbbbbbbbbbbbbbb.
        ...b11bbbbbbbbbbbbbbbbb.
        ...b11bbbbbbbbbbbbbbbbb.
        ...bbbbbbbbbbbbbbbbbbbb.
        ...bbbbbbbbbbbbbbbbbbbb.
        ...bbbbbbbbbbbbbbbbbbbb.
        ...bbbbbbbbbbbbbbbbbbbb.
        ...bbbbbbbbbbbbbbbbbbbb.
        ...bbbbbbbbbbbbbbbbbbbb.
        ...bbbbbbbbbbbbbbbbbbbb.
        ...bbbbbbbbbbbbbbbbbbbb.
        ...bbbbbbbbbbbbbbbbbbbb.
        ...bbbbbbbbbbbbbbbbbbbb.
        ...bbbbbbbbbbbbbbbbbbbb.
        ...bbbbbbbbbbbbbbbbbbbb.
        ...ffffffbbbbbbbbbbbbbb.
        ...ffffffbbbbbbbbbbbbbb.
        ...ffffffbbbbbbbbbbbbbb.
        ...ffffff...............
        ...ffffff...............
        ...ffffff...............
        ...ffffff...............
        ...ffffff...............
        ...ffffff...............
        `, img`
        .........bbb............
        .......bbbbbbb..........
        .......bbbbbbbbb........
        ......bbbbbbbbbbbb......
        .....bbbbbbbbbbbbbb.....
        ....bbbbbbbbbbbbbbbb....
        ...b11bbbbbbbbbbbbbbb...
        ..bb11bbbbbbbbbbbbbbb...
        ...bbbbbbbbbbbbbbbbbb...
        ....bbbbbbbbbbbbbbbbb...
        ....bbbbbbbbbbbbbbbb....
        .....bbbbbbbbbbbbbb.....
        ......bbbbfffbbbb.......
        .......bbfffffbb........
        ........bfffff..........
        .........ffffff.........
        ..........fffff.........
        ..........ffffff........
        ...........fffffff......
        ............ffffff......
        ............fffffff.....
        .............ffffff.....
        ..............ffff......
        ........................
        `, img`
        ........................
        ........................
        ........................
        ffffffffbbbbbbbbbbbbbbb.
        ffffffffbbbbbbbbbbbb11b.
        ffffffffbbbbbbbbbbbb11b.
        ffffffffbbbbbbbbbbbbbbb.
        ffffffffbbbbbbbbbbbbbbb.
        ......bbbbbbbbbbbbbbbbb.
        ......bbbbbbbbbbbbbbbbb.
        ......bbbbbbbbbbbbbbbbb.
        ......bbbbbbbbbbbbbbbbb.
        ......bbbbbbbbbbbbbbbbb.
        ......bbbbbbbbbbbbbbbbb.
        ......bbbbbbbbbbbbbbbbb.
        ......bbbbbbbbbbbbbbbbb.
        ......bbbbbbbbbbbbbbbbb.
        ......bbbbbbbbbbbbbbbbb.
        ......bbbbbbbbbbbbbbbbb.
        ........................
        ........................
        ........................
        ........................
        ........................
        `, img`
        ........bbb.............
        ......bbbbbbb...........
        ......bbbbbbbbb.........
        .....bbbbbbbbbbbb.......
        ....bbbbbbbbbbbbbb......
        ...bbbbbbbbbbbbbbbb.....
        ..b11bbbbbbbbbbbbbbb....
        .bb11bbbbbbbbbbbbbbb....
        ..bbbbbbbbbbbbbbbbbb....
        ...bbbbbbbbbbbbbbbbb....
        ...bbbbbbbbbbbbbbbb.....
        ....bbbbbbbbbbbbbb......
        .....bbbbfffbbbb........
        ......bbfffffbb.........
        .......bfffff...........
        ........ffffff..........
        .........fffff..........
        .........ffffff.........
        ..........fffffff.......
        ...........ffffff.......
        ...........fffffff......
        ............ffffff......
        .............ffff.......
        ........................
        `, img`
        ..bbbbbbbbbbbbbbbbbbbb..
        ..b11bbbbbbbbbbbbbbbbb..
        ..b11bbbbbbbbbbbbbbbbb..
        ..bbbbbbbbbbbbbbbbbbbb..
        ..bbbbbbbbbbbbbbbbbbbb..
        ..bbbbbbbbbbbbbbbbbbbb..
        ..bbbbbbbbbbbbbbbbbbbb..
        ..bbbbbbbbbbbbbbbbbbbb..
        ..bbbbbbbbbbbbbbbbbbbb..
        ..bbbbbbbbbbbbbbbbbbbb..
        ..bbbbbbbbbbbbbbbbbbbb..
        ..bbbbbbbbbbbbbbbbbbbb..
        ..bbbbbbbbbbbbbbbbbbbb..
        ..bbbbbbbbbbbbbbbbbbbb..
        ..bbbbbbbbbbbbbbbbbbbb..
        ..ffffffbbbbbbbbbbbbbb..
        ..ffffffbbbbbbbbbbbbbb..
        ..ffffffbbbbbbbbbbbbbb..
        ..ffffff................
        ..ffffff................
        ..ffffff................
        ..ffffff................
        ..ffffff................
        ..ffffff................
        `],
                200,
                false
            )
            pause(500)
            statusbar2.value += -5
        })
    }
}