
namespace SpriteKind {
    export const li = SpriteKind.create()
    export const LSYwuqi = SpriteKind.create()
    export const Boss = SpriteKind.create()
    export const LSYboujian = SpriteKind.create()
    export const GUI = SpriteKind.create()
}

namespace shengyou_room{

export function main() {
    let LSY鬼: Sprite = null
    let LSYBoss: Sprite = null
    let LSY手雷: Sprite = null
    let LSY导弹: Sprite = null
    let LSY宝剑: Sprite = null
    let lsy勇士: Sprite = null
    tiles.setTilemap(tilemap`级别1`)
    game.splash("打败小怪和BOSS，就胜利。一定要小心！", "作者：黎X佑")
    lsy勇士 = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f f f f d d d d d e e f . . 
    . f d d d d f 4 4 4 e e f . . . 
    . f b b b b f 2 2 2 2 f 4 e . . 
    . f b b b b f 2 2 2 2 f d 4 . . 
    . . f c c f 4 5 5 4 4 f 4 4 . . 
    . . . f f f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
    lsy勇士.setPosition(40, 99)
    controller.moveSprite(lsy勇士)
    scene.cameraFollowSprite(lsy勇士)
    LSY宝剑 = sprites.create(img`
    . . . . . . . 8 . . . . . . . . 
    . . . . . . 8 8 8 . . . . . . . 
    . . . . . . 8 8 8 . . . . . . . 
    . . . . . . 8 8 8 . . . . . . . 
    . . . . . . 8 8 8 . . . . . . . 
    . . . . . . 8 8 8 . . . . . . . 
    . . . . . . 8 8 8 . . . . . . . 
    . . . . . . 8 8 8 . . . . . . . 
    . . . . . . 8 8 8 . . . . . . . 
    . . . 4 4 4 4 4 4 4 4 4 . . . . 
    . . . 4 4 4 9 9 9 4 4 4 . . . . 
    . . . . . . 9 5 9 . . . . . . . 
    . . . . . . 9 5 9 . . . . . . . 
    . . . . . . 9 5 9 . . . . . . . 
    . . . . . . 9 9 9 . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.LSYboujian)
    tiles.placeOnRandomTile(LSY宝剑, sprites.castle.tileGrass1)
    for (let index = 0; index < 4; index++) {
        LSY导弹 = sprites.create(img`
        .........................
        ..............ffff.......
        .2..fffffffffffeefff.....
        222.fee7eeee7eeee7eff....
        .e..fe177771111e1111fff..
        .ee.f7177771777ee771eefff
        ..eef71711711117111177eef
        ....f71777777e1717777eeef
        ....fe1777711117177eeefff
        ....fee77777eeee1111fff..
        ....fffffffffffeee7ff....
        ..............feefff.....
        ..............ffff.......
        .........................
        .........................
        .........................
        `, SpriteKind.LSYwuqi)
        tiles.placeOnRandomTile(LSY导弹, sprites.castle.tilePath5)
    }
    for (let index = 0; index < 4; index++) {
        LSY手雷 = sprites.create(img`
        . . . . . . f f f . . . . . . . 
        . . . . . . f . f . . . . . . . 
        . . . . . . f f f . . . . . . . 
        . . . . . . . . f . . . . . . . 
        . . . . . . . f f f . . . . . . 
        . . . . . 7 7 7 7 7 7 7 . . . . 
        . . . . . 7 e f e f e 7 . . . . 
        . . . . . 7 f f f f f 7 . . . . 
        . . . . . 7 e f e f e 7 . . . . 
        . . . . . 7 f f f f f 7 . . . . 
        . . . . . 7 e f e f e 7 . . . . 
        . . . . . 7 f f f f f 7 . . . . 
        . . . . . 7 e f e f e 7 . . . . 
        . . . . . 7 f f f f f 7 . . . . 
        . . . . . 7 7 7 7 7 7 7 . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.LSYwuqi)
        tiles.placeOnRandomTile(LSY手雷, sprites.swamp.swampTile2)
    }
    LSYBoss = sprites.create(img`
    .....222222222......
    .....2fff1fff2......
    .....2ff1f1ff2......
    .....2f1fff1f2......
    .....2f11111f2......
    ..fff2fffffff2ffff..
    ..fdd222222222fddf..
    ..fddff22222fffddf..
    ..ff2f2222222f2fff..
    ..2f2f2222222f2f2...
    ..22fff22222fff22...
    ..22fff22222fff22...
    ..222f2222222f222...
    ..222f2222222f222...
    ..222f2222222f222...
    ..fffffffffffffff...
    ..fffffffffffffff...
    ..ff22222222222ff...
    ....22222222222.....
    ....22222.22222.....
    ....2222...2222.....
    ....222.....222.....
    ....222.....222.....
    ....fff.....fff.....
    ...ffff.....ffff....
    `, SpriteKind.Enemy)
    sprite_hp.setHp(LSYBoss, 15)
    LSYBoss.setPosition(119, 100)
    LSYBoss.follow(lsy勇士, 7)
    for (let index = 0; index < 1; index++) {
        LSY鬼 = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .....fffc1111111f.......
        ...fc111cd1111111f......
        ...f1b1b1b1111dddf......
        ...fbfbffcf11fcddf..c...
        ......fcf111111bbf.cc...
        .......ccbdb1b1fcf.cc...
        .......fffbfbfdff.ccc...
        ........ffffffff..cc....
        ........fffffffffff.....
        .........fffffc111cf....
        .........fffff1b1b1f....
        ..........ffffbfbfbf....
        ...........ffff.........
        ........................
        ........................
        ........................
        `, SpriteKind.GUI)
        sprite_hp.setHp(LSY鬼, 5)
        LSY鬼.follow(lsy勇士, 4)
        LSY鬼.setPosition(13, 102)
        if (sprite_hp.hpOfSprite(LSY鬼) == 0 && sprite_hp.hpOfSprite(LSYBoss) == 0) {
            LSY鬼.setImage(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . 1 . . . . 
            . . . . 1 . 1 . 1 . . . . . . . 
            . . . . 1 . . . . . . . . . . . 
            . . . . 1 . . . . . . . 1 . . . 
            . . . . 1 . . 1 . 1 1 . . . . . 
            . . . . . . . . . . . . . . . . 
            . . 1 . . . 1 . 1 . . . 1 1 . . 
            . . . . . . . . 1 . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . 1 . . . . 1 . . . 1 . . 1 . . 
            . 1 . . . . . . . . . . . . . . 
            . . . . . . . . 1 . . . . . . . 
            . . . . . 1 . . . . . . . . . . 
            `)
            LSYBoss.setImage(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . 1 . . . . . . 
            . . . . . 1 . . . . . . . 1 . . 
            . . . . . . . . . . . . . . . . 
            . . 1 . . . . 1 . . . . 1 . . . 
            . . . . 1 . . . . . . . . . . . 
            . . . . . . . . 1 . . 1 . . . . 
            . . . . . . 1 . . . . . . . . . 
            . . . 1 . . . . . . . . . . 1 . 
            . . . . . . . . 1 . . 1 . . . . 
            . 1 . . . . . . 1 . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . 1 . . . . . . . 
            . . . . . 1 . . . . . . . . . . 
            . . . . . . . . . . . . . 1 . . 
            . . . . . . . . . . . . . . . . 
            `)
            gamejam.roomFinished(true)
        }
    }

    controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
        LSY导弹 = sprites.create(img`
        .........................
        ..............ffff.......
        .2..fffffffffff7efff.....
        222.fee7777eee77eeeff....
        .e..fe71777ee1117111fff..
        .ee.f77177777177777177fff
        ..eef7717111711171117eeef
        ....f7717777777171777eeef
        ....fee17777e1117111eefff
        ....feee777eeeee7777fff..
        ....fffffffffffee77ff....
        ..............feefff.....
        ..............ffff.......
        .........................
        .........................
        .........................
        `, SpriteKind.Player)
        tiles.placeOnRandomTile(LSY导弹, assets.tile`myTile9`)
        LSY导弹.sayText("3")
        pause(1000)
        LSY导弹.sayText("2")
        pause(1000)
        LSY导弹.sayText("1")
        pause(1000)
        LSY导弹.sayText("B o o M")
        pause(1000)
        LSY导弹.destroy()
        sprite_hp.changeHpOfSpriteBy(LSYBoss, -1)
        sprite_hp.changeHpOfSpriteBy(LSY鬼, -2)
        LSYBoss.x += -17
        LSY鬼.x += -19
    })
    sprites.onOverlap(SpriteKind.Player, SpriteKind.GUI, function (sprite, otherSprite) {

    })
    sprites.onOverlap(SpriteKind.Player, SpriteKind.LSYwuqi, function (sprite, otherSprite) {
        otherSprite.destroy()
    })
    controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
        LSY手雷 = sprites.create(img`
        . . . . . . f f f . . . . . . . 
        . . . . . . f . f . . . . . . . 
        . . . . . . f f f . . . . . . . 
        . . . . . . . . f . . . . . . . 
        . . . . . . . f f f . . . . . . 
        . . . . . 7 7 7 7 7 7 7 . . . . 
        . . . . . 7 e f e f e 7 . . . . 
        . . . . . 7 f f f f f 7 . . . . 
        . . . . . 7 e f e f e 7 . . . . 
        . . . . . 7 f f f f f 7 . . . . 
        . . . . . 7 e f e f e 7 . . . . 
        . . . . . 7 f f f f f 7 . . . . 
        . . . . . 7 e f e f e 7 . . . . 
        . . . . . 7 f f f f f 7 . . . . 
        . . . . . 7 7 7 7 7 7 7 . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.LSYwuqi)
        tiles.placeOnRandomTile(LSY手雷, sprites.builtin.forestTiles0)
        LSY手雷.sayText("3")
        pause(1000)
        LSY手雷.sayText("2")
        pause(1000)
        LSY手雷.sayText("1")
        pause(1000)
        LSY手雷.sayText("B o o M")
        pause(1000)
        LSY手雷.destroy()
        sprite_hp.changeHpOfSpriteBy(LSYBoss, -1)
        sprite_hp.changeHpOfSpriteBy(LSY鬼, -3)
        LSYBoss.x += 16
        LSY鬼.x += 18
    })
    info.onLifeZero(function () {
        game.over(false, effects.melt)
        lsy勇士.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . 1 1 . . . . . . 
        . . . . 1 . . . . 1 . 1 . . . . 
        . 1 . . . . . . . . . . . . . . 
        . . . . 1 . . . 1 . . . . . . . 
        . . . . . . . . . . 1 . . . . . 
        . . . . . . . 1 1 . 1 . . 1 . . 
        . . . . 1 1 1 1 . . 1 . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . 1 . . . 
        . . . . 1 . . . . 1 . . . . . . 
        . . . . 1 . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `)
    })
    sprites.onOverlap(SpriteKind.Player, SpriteKind.LSYboujian, function (sprite, otherSprite) {
        lsy勇士.setImage(img`
        ......ffff..............
        ....fff22fff.1ddd.......
        ...fff2222ff1ddbdd......
        ..fffeeeeee1dddbddd.....
        ..ffe2222221dddbddd.....
        ..fe2ffffff21ddbdd......
        ..ffffeeeeff1ddbdd......
        .ffefbf44fbf11dbdd......
        .fee41fddf14e1dbd.......
        ..ffffdddddee1ddd.......
        .fddddf444eefceee.......
        .fbbbbf2222f4c252.......
        .fbbbbf2222fd4c2........
        ..fccf45544f44c4........
        ...ffffffff.............
        .....ff..ff.............
        `)
        LSY宝剑.destroy()
    })
    controller.menu.onEvent(ControllerButtonEvent.Pressed, function () {
        lsy勇士.setImage(img`
        ...........ff..........
        .........ff22ff........
        .......fff2222fff......
        ......fff222222fff.....
        ......fff222222fff.....
        ......feeeeeeeeeeff....
        .....ffe22222222eff....
        .....fffffeeeefffff....
        ....fdfefbf44fbfeff....
        ....fbfe41fddf14ef.....
        ....fbffe4dddd4efe.....
        ....fcfef22222f4e......
        .....ff4f44554f4c......
        ........ffffffd2c......
        .........ffffe252c.....
        ..............eeec.....
        ..............ddd1.....
        ..............dbd1.....
        .............ddbd11....
        .............ddbdd1....
        .............ddbdd1....
        ............dddbddd1...
        ............dddbddd1...
        .............ddbdd1....
        ..............ddd1.....
        .......................
        .......................
        `)
        pause(500)
        lsy勇士.setImage(img`
        ..........ffff...........
        ........fff22fff.........
        .......fff2222ff1ddd.....
        ......fffeeeeee1ddbdd....
        ......ffe222221dddbddd...
        ......fe2fffff1dddbddd...
        ......ffffeeeef1ddbdd....
        .....ffefbf44fb1ddbdd....
        .....fee41fddf111dbdd....
        ......ffffddddde1dbd.....
        .....fddddf444ee1ddd.....
        .....fbbbbf2222fceee.....
        .....fbbbbf2222fc252.....
        ......fccf45544f4c2......
        .......ffffffff..c4......
        .........ff..ff..........
        `)
        sprite_hp.changeHpOfSpriteBy(LSY鬼, -2)
        sprite_hp.changeHpOfSpriteBy(LSYBoss, -1)
        LSYBoss.y += 16
        LSY鬼.y += 18
    })
    sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
        sprite_hp.changeHpOfSpriteBy(LSY鬼, -1)
        LSY鬼.sayText("NO")
        pause(500)
        sprite_hp.changeHpOfSpriteBy(LSYBoss, -2)
        LSYBoss.sayText("No")
        pause(500)
    })
    sprites.onOverlap(SpriteKind.Player, SpriteKind.Boss, function (sprite, otherSprite) {

    })
  

}
}